name: jangquranaksunna
description: "Application mobile pour la plateforme d'enseignement islamique JangQuranAkSunna"
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Navigation
  cupertino_icons: ^1.0.6
  go_router: ^12.1.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  
  # State Management
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  equatable: ^2.0.5
  
  # HTTP & API
  http: ^1.1.0
  dio: ^5.3.2
  retrofit: ^4.0.3
  json_annotation: ^4.8.1
  
  # Local Storage & Database
  drift: ^2.14.1
  sqlite3_flutter_libs: ^0.5.15
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  
  # Media & Content
  video_player: ^2.8.1
  audio_service: ^0.18.12
  just_audio: ^0.9.36
  just_audio_background: ^0.0.1-beta.11
  flutter_pdfview: ^1.3.2
  cached_network_image: ^3.3.0
  flutter_cache_manager: ^3.3.1
  
  # Authentication & Security
  google_sign_in: ^6.1.5
  crypto: ^3.0.3
  encrypt: ^5.0.1
  
  # UI Components
  flutter_svg: ^2.0.9
  shimmer: ^3.0.0
  pull_to_refresh: ^2.0.0
  infinite_scroll_pagination: ^4.0.0
  flutter_rating_bar: ^4.0.1
  
  # Permissions & Platform
  permission_handler: ^11.0.1
  device_info_plus: ^9.1.1
  package_info_plus: ^4.2.0
  connectivity_plus: ^5.0.2
  
  # Firebase & Notifications
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.9
  firebase_crashlytics: ^3.4.8
  firebase_analytics: ^10.7.4
  flutter_local_notifications: ^16.3.0
  
  # Downloads & File Management
  path: ^1.8.3
  mime: ^1.0.4
  open_filex: ^4.3.4
  
  # Utilities
  url_launcher: ^6.2.1
  share_plus: ^7.2.1
  image_picker: ^1.0.4
  flutter_markdown: ^0.6.18
  webview_flutter: ^4.4.2
  
  # Islamic Features
  adhan: ^3.0.1
  hijri: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation
  build_runner: ^2.4.7
  retrofit_generator: ^8.0.4
  json_serializable: ^6.7.1
  drift_dev: ^2.14.1
  
  # Linting & Analysis
  flutter_lints: ^3.0.1
  very_good_analysis: ^5.1.0
  
  # Testing
  bloc_test: ^9.1.5
  mocktail: ^1.0.1
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - assets/images/
    - assets/icons/
    - assets/audio/
    - assets/quran/
    - assets/translations/
  
  # Fonts
  fonts:
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri-Regular.ttf
        - asset: assets/fonts/Amiri-Bold.ttf
          weight: 700
        - asset: assets/fonts/Amiri-Italic.ttf
          style: italic
    - family: Scheherazade
      fonts:
        - asset: assets/fonts/Scheherazade-Regular.ttf
        - asset: assets/fonts/Scheherazade-Bold.ttf
          weight: 700

flutter_intl:
  enabled: true
  class_name: S
  main_locale: fr
  arb_dir: lib/l10n
  output_dir: lib/generated
