server:
  port: 8080
  forward-headers-strategy: framework

spring:
  datasource:
    url: jdbc:h2:mem:jangquranaksunna;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    open-in-view: false
    show-sql: false
  h2:
    console:
      enabled: true
      path: /h2-console
  flyway:
    enabled: false

logging:
  level:
    org.springframework: INFO
    org.hibernate.SQL: INFO

security:
  jwt:
    secret: dev-secret-change-me-please-32bytes-minimum-secret-key
    ttl-seconds: 86400
